### ISSUE TITLE
Slack通知できるようにする

### ISSUE THREAD

**Issue by yuji38kwmt** [kurusugawa-computer/annofab-cli#32]
* タスクの枯渇をSlack通知する(複数プロジェクト)
* 可視化情報を通知できるようにする

**Comment by exoego** [comment]
特定のコマンドを実行したときに、その結果をSlackに通知するんでしょうか？
それはCLIツールの役割を超えていませんか？

**Comment by yuji38kwmt** [comment]
>それはCLIツールの役割を超えていませんか？
そうですね、確かに役割は超えていますね。

「タスクの枯渇情報などをSlackと連携する」というユースケースはよくあると思うので、簡単に通知できるとよいと思いました。

**Comment by yuji38kwmt** [comment]
annofabcliの範囲を超えているため、close
