### ISSUE TITLE
[タスク] 複数のタスクを作業中から休憩中に変更するコマンドを作る

### ISSUE THREAD

**Issue by yuji38kwmt** [kurusugawa-computer/annofab-cli#776]
# 背景
以前`task reject`コマンドの不具合で、「操作対象のタスクがすべて「作業中」状態になり、作業時間が膨大に増えてしまう」という事象が発生しました。

その際、「作業中状態のタスクを休憩中状態にする」コマンドが欲しかったです。

したがって、それを対応するコマンドが欲しいです。

# 欲しいコマンド

```
$ annofabcli task change_status_to_break --project_id  p1 --task_id t1 t2
```

### 必須の引数
* `--project_id`
* `--task_id`

### オプショナルな引数
* `--task_query`
* `--parallelism`
* `--yes`

### 前提条件
* 操作対象タスクは、タスクの状態が「作業中」か「休憩中」のときのみ

※もちろん不具合を出さないのがベストですが

**Comment by pfe171** [comment]
> 操作対象タスクは、タスクの状態が「作業中」か「休憩中」のときのみ

とありますが、以下のうち今回のコマンドで実現したい（しなくてよい）操作はどれになるでしょうか？

1. 作業中→休憩中
2. 作業中→保留中
3. 休憩中→作業中
4. 休憩中→保留中

**Comment by yuji38kwmt** [comment]
混乱させるタイトルですみません。

作業中から休憩中にするコマンドが欲しいです。

**Comment by yuji38kwmt** [comment]
完了したためクローズ
